# Generated by Django 5.2.3 on 2025-07-31 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('SKU', models.CharField(max_length=15, unique=True, verbose_name='SKU')),
                ('vendor', models.CharField(max_length=40, verbose_name='Vendor')),
                ('location', models.CharField(max_length=35, verbose_name='Location')),
                ('sub_location', models.CharField(blank=True, max_length=35, null=True, verbose_name='Sub-location')),
                ('location_detail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location Detail')),
                ('amount_in_stock', models.PositiveIntegerField(verbose_name='Amount in Stock')),
                ('units', models.CharField(max_length=80, verbose_name='Units')),
                ('vendor_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vendor Quantity')),
                ('date_opened', models.DateField(default=django.utils.timezone.now, verbose_name='Date Opened')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('storage_temperature', models.CharField(blank=True, max_length=20, null=True, verbose_name='Storage Temperature')),
                ('storage_instructions', models.TextField(blank=True, null=True, verbose_name='Storage Instructions')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('URL', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
        ),
    ]
