# Generated by Django 5.2.3 on 2025-08-26 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('vendor', models.CharField(max_length=40, verbose_name='Vendor')),
                ('amount_requested', models.PositiveIntegerField(verbose_name='Amount Requested')),
                ('vendor_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vendor Quantity')),
                ('units', models.CharField(max_length=80, verbose_name='Units')),
                ('URL', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Solution Name')),
                ('SKU', models.CharField(max_length=15, unique=True, verbose_name='SKU')),
                ('vendor', models.CharField(max_length=40, verbose_name='Vendor')),
                ('location', models.CharField(max_length=35, verbose_name='Location')),
                ('sub_location', models.CharField(blank=True, max_length=35, null=True, verbose_name='Sub-location')),
                ('recipe_instructions', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recipe Instructions')),
                ('amount_in_stock', models.PositiveIntegerField(verbose_name='Amount in Stock')),
                ('units', models.CharField(max_length=80, verbose_name='Units')),
                ('URL', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Usage_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('SKU', models.CharField(max_length=15, verbose_name='SKU')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('vendor', models.CharField(max_length=40, verbose_name='Vendor')),
                ('quantity_used', models.IntegerField(verbose_name='Quantity Used')),
                ('stock_remaining', models.IntegerField(verbose_name='Stock Remaining')),
                ('units', models.CharField(max_length=50, verbose_name='Units')),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Item Name'),
        ),
    ]
