# Generated by Django 5.2.3 on 2025-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_new_order_solutions_usage_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reorder',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Reorder'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vendor_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vendor Qty'),
        ),
    ]
