# Generated by Django 5.2.3 on 2025-10-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_reorder_alter_inventory_vendor_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False},
        ),
    ]
