# Generated by Django 5.2.3 on 2025-10-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False, 'ordering': ['item_name']},
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory_inventory',
        ),
    ]
