# Generated by Django 5.2.3 on 2025-10-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_options_alter_inventory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': True, 'ordering': ['item_name']},
        ),
    ]
