# Generated by Django 5.2.3 on 2025-10-23 19:17

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='URL',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='SKU',
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_opened',
            field=models.DateField(blank=True, null=True, verbose_name='Date Opened'),
        ),
        migrations.CreateModel(
            name='InventoryLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.CharField(blank=True, default=inventory.models.generate_unique_sku, max_length=15, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
