# Generated by Django 5.2.3 on 2025-10-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_create_inventorylogentry_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='reorder',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=100),
        ),
    ]
