# Generated by Django 5.2.3 on 2025-10-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventory_reorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='units',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vendor',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Vendor'),
        ),
    ]
