# Generated by Django 5.2.3 on 2025-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventorylogentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='inventory',
            name='planned_reactions',
            field=models.PositiveIntegerField(blank=True, help_text='Number of reactions planned for upcoming session (optional)', null=True, verbose_name='Planned Reactions'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_override',
            field=models.IntegerField(blank=True, help_text='Manual override for reorder threshold (persists until cleared)', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='students_per_reaction',
            field=models.PositiveIntegerField(blank=True, help_text='How many students run each reaction (used to compute total needed)', null=True, verbose_name='Students per Reaction'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='units_per_reaction',
            field=models.FloatField(blank=True, help_text='How many units of this item one reaction consumes (e.g. 1, 0.5)', null=True, verbose_name='Units per Reaction'),
        ),
    ]
