# Generated by Django 5.2.3 on 2025-11-14 18:33
from django.db import migrations
import uuid

def dedupe_skus(apps, schema_editor):
    Inventory = apps.get_model("inventory", "Inventory")

    seen = set()
    # Order by id so fixes are deterministic
    for item in Inventory.objects.all().order_by("id"):
        if not item.sku or item.sku in seen:
            item.sku = uuid.uuid4().hex[:12].upper()
            item.save(update_fields=["sku"])
        seen.add(item.sku)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_inventory_reorder_level_and_more'),  # ← update this to your actual previous migration name
    ]

    operations = [
        migrations.RunPython(dedupe_skus, migrations.RunPython.noop),
    ]
