# Generated by Django 5.2.3 on 2025-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_populate_unique_skus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='units',
            field=models.CharField(blank=True, help_text='Human-readable unit name (e.g. "each", "mL", "g"). If units_per_reaction is set and units is blank, units will default to "each".', max_length=80, null=True, verbose_name='Units'),
        ),
    ]
